### GET gpio info
GET http://192.168.20.182/api/led_info

### GET brightness (all channels)
GET http://192.168.20.182/api/brightness

### GET brightness (Channel 0)
GET http://192.168.20.182/api/brightness?ch=0

### Set brightness (Channel 0 to 20%)
POST http://192.168.20.182/api/brightness?ch=0&value=20
Accept: application/json

### GET power status (all channels)
GET http://192.168.20.182/api/power

### Turn Channel 0 OFF
POST http://192.168.20.182/api/power?ch=0&value=off
Accept: application/json

### Turn Channel 0 ON
POST http://192.168.20.182/api/power?ch=0&value=on
Accept: application/json

### Configure WiFi and Restart
POST http://192.168.20.182/api/wifi?ssid=MyNetwork&password=MyPassword
Accept: application/json